security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        api_key_user_provider:
            id: AppBundle\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/user
            provider: api_key_user_provider
            stateless: false
            simple_preauth:
                authenticator: AppBundle\Security\ApiKeyAuthenticator
