# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    api:
        classes:
            - AppBundle\Api\Transport\GoogleDirection
            - AppBundle\Service\Velov\Velov
            - AppBundle\Api\Weather\WeatherInfoClimat
        google_direction:
            url: "https://maps.googleapis.com/maps/api/directions/"
            key: "%google_api_key.direction%"
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests,Model}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Service\Velov\Velov:
        public: true

    AppBundle\Api\Transport\GoogleDirection:
      public: true
      arguments:
        - "%api%"

    AppBundle\Resolver\ApiServiceResolver:
      public: true
      arguments:
        - "@service_container"
        - "%api%"

    AppBundle\Api\Weather\WeatherInfoClimat:
      public: true

    AppBundle\Security\UserProvider:
        public: true

    AppBundle\Security\SecurityLoginHandler:
        public: true

    AppBundle\Provider\UserTokenProvider:
        public: true

    AppBundle\ArgumentResolver\UserTokenValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    AppBundle\Provider\RequestLocationProvider:
        public: true

    AppBundle\ArgumentResolver\RequestLocalisationValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    AppBundle\Handler\ApiExceptionHandler:
        arguments:
            $disabled: '%app.disable_api_exception_handler%'
        public: true

    AppBundle\Collector\ApiExceptionCollector:
        public: true

    AppBundle\Service\GoogleClient:
        public: true
        arguments:
            $googleId: '%oauth.google_id%'

    AppBundle\EventListener\ApiExceptionHandlerEventListener:
        arguments:
            $isDev: '%kernel.debug%'
            $handlingGeneralException: '%app.handling_general_exception%'
        tags:
            -
                name: kernel.event_listener
                event: !php/const:Symfony\Component\HttpKernel\KernelEvents::EXCEPTION
                method: onKernelException
            -
                name: kernel.event_listener
                event: !php/const:AppBundle\AppEvents::API_CATCH_EXCEPTION
                method: onApiException