version: '3.0'
services:
    mysql:
        image: mysql:5.7
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            static-network:

    php:
        build:
            context: ./dockerfiles/php
            args:
                - USER=${USER}
                - USER_GID=${USER_GID}
                - USER_UID=${USER_UID}
        volumes:
            - ./app:/usr/share/nginx/html
        networks:
            static-network:
        links:
            - mysql
        depends_on:
            - mysql

    nginx:
        build:
            context: dockerfiles/nginx/php
        volumes:
            - ./app:/usr/share/nginx/html
        links:
            - php
        depends_on:
            - php
        networks:
            static-network:
                ipv4_address: 172.40.0.10

networks:
    static-network:
        ipam:
            config:
                - subnet: 172.40.0.0/24

volumes:
    mysql-data:
